var slides = ["milk",
	      "lemon",
	      "fruit",
	      "mushrooms",
	      "baby potatoes",
	      "garlic",
	      "carrots",
	      "onion (red and yellow)",
	      "zuchini",
	      "parmesan",
	      "banana",
	      "sweet potatoes",
	      "oats",
	      "fresh lasagna",
	      "corn",
	      "poblano or other pepper",
	      "crushed tomato",
	      ];