var slides = ["bananas",
	      "grapes",
	      "fruit",
	      "oranges",
	      "tuna",
	      "eggs",
	      "chicken",
	      "peas",
	      "potato",
	      "onion",
	      "snax",
	      "milk",
	      "lemon",
	      "garlic",
	      "snorlax",
	      "chili oil",
	      "vegetable",
	      "coffee",
	      "snack carrots",
	      "artichoke",
	      "sausage"
	      ];