var slides = ["bananas",
	      "fruit",
	      "chicken",
	      "lunch meat",
	      "rice",
	      "quinoa",
	      "brocoli",
	      "sweet potato",
	      "carrot",
	      "eggs",
	      "onion",
	      "snax",
	      "milk",
	      "garlic",
	      "sausage",
	      "yoghurt",
	      "mint",
	      "spinach",
	      "cherry tomatoes",
	      "arugula",
	      "pie crust",
	      "parmesan",
	      "asparagus",
	      "lemon",
	      "turkey bacon",
	      ];